<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>GoodbyeDPI-GUI</AssemblyName>
    <RootNamespace>GoodbyeDPI_GUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.0.0</Version>
    <Authors>Toprak</Authors>
    <Description>GoodbyeDPI V2 GUI - Modern GUI for GoodbyeDPI Turkey Edition</Description>
    <Copyright>Made with ♥ by Toprak</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

</Project>

